spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7086/eureka/
  instance:
    hostname: localhost
