spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/microservices?useTimezone=true&serverTimezone=UTC '
  jpa:
    hibernate:
      use-new-id-generator-mappings: 'false'
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    hostname: localhost
